---

define: &containerPort 80

service:
  type: ClusterIP
  enabled: true
  servicePort: 80
  containerPort: *containerPort
  extraLabels: {}

deployment:
  memoryRequest: null
  cpuRequest: null
  memoryLimit: null
  cpuLimit: null
  port: *containerPort
  strategy:
    type: Replace
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

image:
  repositorySettings:
    isPrivate: false
    secretName: null
  repository: nginx
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false
  hostName: toto.lan
  extraLabels: {}
  annotations: {}
  tls:
    enabled: true
    secretName: ""
  # For Ingress CRD
  ingressClassName: istio

# env variables
variables:
  secret: {}
  # user: "username"
  # password: "hugepassword"
  nonSecret: {}
#    author: name
#    app: 1

# horizontal autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  avgCpuUtilization: 50

# startupProbe
startupProbeEnabled: false
startupProbe: {}
# httpGet:
#   path: "/"
#   port: *containerPort
# periodSeconds: 10
# failureThreshold: 20
# timeoutSeconds: 1

# readinessProbe
readinessProbeEnabled: false
readinessProbe: {}
# httpGet:
#   path: "/"
#   port: *containerPort
# initialDelaySeconds: 20
# periodSeconds: 30
# failureThreshold: 2
# timeoutSeconds: 3

# livenessProbe
livenessProbeEnabled: false
livenessProbe: {}
# enabled: true
# httpGet:
#   path: "/"
#   port: *containerPort
# initialDelaySeconds: 20
# periodSeconds: 60
# failureThreshold: 1
# timeoutSeconds: 3


persistence:
  enabled: false
  volumes: []
  # - name: "data"
  #   storageClassName: "longhorn" # leave empty if you want to use default
  #   size: "5Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
  #   pvcClaim: "" # leave empty unless if you want to use an existing PVC
  #   containerMount: "/data"
  # - name: "logs"
  #   storageClassName: "" # leave empty if you want to use default
  #   size: "1Gi" # We recommend to allocate a minimum of 1GB if you do not use attachments
  #   pvcClaim: "" # leave empty unless if you want to use an existing PVC
  #   containerMount: "/var/log"
  # - name: "temp"
  #   pvcClaim: "existing" # leave empty unless if you want to use an existing PVC
  #   containerMount: "/testest"
tests:
  classicHttp:  # default helm test method
    enabled: true
  curlHostHeader:  # curl using ingress.hostName as Host in header
    enabled: true
    path: ""
