{{ if .Values.variables.secret }}
{{- $dot := . }}
{{- range $index, $value := .Values.variables.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dot.Release.Name }}-{{ $index | lower | replace "_" "-" }}
data:
  secret: {{ $value | toString | b64enc }}
---
{{ end }}
{{ end }}