{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  {{- if .Values.service.extraLabels }}
    {{ .Values.service.extraLabels | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - targetPort: {{ .Values.deployment.port }}
    port: {{ .Values.service.servicePort }}
  type: {{ .Values.service.type }}
{{- end }}